services:
  account:
    build:
      dockerfile: ./account/Dockerfile
      target: devel
    volumes:
      - ./account:/app/account
    ports:
      - 8880:8880

  account-db:
    image: mariadb:lts-ubi9
    volumes:
      - account-vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: what_would_it_be_i_wonder
      MARIADB_PASSWORD: perhaps_i_should_try_this_one

  outlet:
    build:
      dockerfile: ./outlet/Dockerfile
      target: devel
    ports:
      - 8881:8880
    volumes:
      - ./outlet:/app/outlet

volumes:
  account-vol:

