services:
  gateway:
    image: caddy:2.10-alpine
    ports:
      - 8080:80
    volumes:
      - ./etc/caddy:/etc/caddy
      - caddy-vol:/data

  account:
    build:
      dockerfile: ./account/Dockerfile
      target: devel
    volumes:
      - ./account:/app/account
      - ./lib:/app/lib
    env_file: 
      - path: "./account/.env"
        required: true
  account-db:
    image: mariadb:lts-ubi9
    volumes:
      - account-vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: what_would_it_be_i_wonder
      MARIADB_USER: goodyapp
      MARIADB_PASSWORD: perhaps_i_should_try_this_one
      MARIADB_DATABASE: goody

  catalog:
    build:
      dockerfile: ./catalog/Dockerfile
      target: devel
    volumes:
      - ./catalog:/app/catalog
      - ./lib:/app/lib
    env_file: 
      - path: "./catalog/.env"
        required: true
  catalog-db:
    image: mariadb:lts-ubi9
    volumes:
      - catalog-vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: what_would_it_be_i_wonder
      MARIADB_USER: goodyapp
      MARIADB_PASSWORD: perhaps_i_should_try_this_one
      MARIADB_DATABASE: goody

volumes:
  caddy-vol:
  account-vol:
  catalog-vol:

